# Generated by Django 4.2.6 on 2023-10-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('tax_code', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(default=11111111, max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='position',
            name='job_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
