# Generated by Django 4.2.6 on 2023-10-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=50)),
                ('tax_code', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='position',
            name='job_description',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
