# Generated by Django 4.2.6 on 2023-11-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('hr', '0002_position_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.CharField(max_length=200),
        ),
    ]
