# Generated by Django 4.2.6 on 2023-16-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name='position',
            name='job_description',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
