# Generated by Django 4.2.6 on 2023-10-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_company_position_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone_number',
            field=models.DateField(blank=True, null=True),
        ),
    ]
