# Generated by Django 4.2.6 on 2023-10-13 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(default='', max_length=151),
        ),
        migrations.AddField(
            model_name='position',
            name='job_description',
            field=models.CharField(default='', max_length=500),
        ),
    ]
