# Generated by Django 4.2.6 on 2023-10-16 19:38

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_company_employee_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
