# Generated by Django 4.2.6 on 2023-10-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_employee_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='job_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
