# Generated by Django 4.2.6 on 2023-10-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_employee_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.DateField(default=' ', max_length=20),
        ),
    ]
