# Generated by Django 4.2.6 on 2023-10-23 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('hr', '0003_position_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='monthly_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='MonthlySalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.DateField()),
                ('salary', models.IntegerField()),
                ('bonus', models.IntegerField(blank=True, null=True)),
                (
                    'employee',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
    ]
