# Generated by Django 4.2.6 on 2023-10-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('hr', '0004_position_monthly_rate_monthlysalary'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysalary',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
