# Generated by Django 4.2.6 on 2023-12-06 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('hr', '0006_position_job_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='department',
            name='parent_department',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='hr.department',
                verbose_name='Parent department',
            ),
        ),
        migrations.AlterField(
            model_name='position',
            name='department',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='hr.department', verbose_name='Department'
            ),
        ),
    ]
