# Generated by Django 4.2.6 on 2023-11-05 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('hr', '0006_position_job_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='cv',
            field=models.FileField(blank=True, help_text='PDF, DOC, or DOCX', null=True, upload_to='cvs/'),
        ),
        migrations.AlterField(
            model_name='position',
            name='department',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='hr.department', verbose_name='Department'
            ),
        ),
    ]
