# Generated by Django 4.2.6 on 2023-12-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('hr', '0007_alter_company_address_alter_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='department',
            name='name_uk',
            field=models.CharField(max_length=200, null=True, verbose_name='name'),
        ),
    ]
