# Generated by Django 4.2.7 on 2023-12-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('hr', '0007_employee_avatar_employee_cv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='avatar',
            field=models.ImageField(blank=True, default='static/img/logo.png', null=True, upload_to='avatars/'),
        ),
    ]
