# Generated by Django 4.2.7 on 2023-12-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('hr', '0008_alter_employee_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
