# Generated by Django 4.2.6 on 2023-11-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_alter_company_name_alter_department_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='department',
            name='name_uk',
            field=models.CharField(max_length=200, null=True, verbose_name='name'),
        ),
    ]
