# Generated by Django 4.2.6 on 2023-11-11 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_department_name_en_department_name_uk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='parent_department_en',
        ),
        migrations.RemoveField(
            model_name='department',
            name='parent_department_uk',
        ),
    ]
