# Generated by Django 4.2.6 on 2023-11-07 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_employee_avatar_employee_cv_and_more'),
        ('hr', '0009_department_name_en_department_name_uk'),
    ]

    operations = [
    ]
