# Generated by Django 4.2.6 on 2023-11-07 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_merge_20231107_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='department',
            name='name_uk',
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_code',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='department',
            name='parent_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.department'),
        ),
        migrations.AlterField(
            model_name='position',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='position',
            name='monthly_rate',
            field=models.IntegerField(default=0),
        ),
    ]
