# Generated by Django 4.2.6 on 2023-11-14 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_merge_20231115_0030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='department',
            name='name_uk',
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
