# Generated by Django 4.2.6 on 2023-11-07 14:28

from django.db import migrations, models
import hr.models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0011_remove_department_name_en_remove_department_name_uk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(null=True, upload_to=hr.models.company_logo_upload_path),
        ),
    ]
