from celery import shared_task
from django.core.mail import send_mail
from hr.models import Employee
from django.utils import timezone
from datetime import timedelta
from general.models import RequestStatistics


@shared_task
def send_password_reset_emails():
    next_month = timezone.now().date() + timedelta(days=30)
    subject = "Зміна паролю необхідна"
    message_template = "Дорогий {}, будь ласка, змініть свій пароль до {}."

    for user in Employee.objects.all():
        message = message_template.format(user.username, next_month.strftime('%Y-%m-%d'))
        send_mail(
            subject,
            message,
            'from@example.com',
            [user.email],
            fail_silently=False,
        )

@shared_task
def send_daily_summary():
    start_time = timezone.now() - timedelta(days=1)
    end_time = timezone.now()
    data = RequestStatistics.objects.filter(timestamp__range=(start_time, end_time))

    subject = "Статистика запитів за день"
    message = ''

    for record in data:
        message += f'Number of requests generated by {record.user}: {record.requests}\n Number of requests that returned an exception: {record.exception}\n'

    from_email = "celery@example.com"
    recipient_list = list(Employee.objects.filter(is_superuser=True).values_list('email'))

    send_mail(
        subject,
        message,
        from_email,
        recipient_list,
        fail_silently=False,
    )

    send_daily_summary.apply_async(args=[], kwargs={}, countdown=10)