# Generated by Django 4.2.7 on 2023-12-04 11:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_remove_requeststatistics_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requeststatistics',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
